// ── PDF Builder ─────────────────────────────────────────────────────────────────
// Factory that wraps jsPDF with layout helpers used by every generator.
// Returns a builder object (b) used like: b.center(...), b.left(...), etc.
// Call b.build() at the end to get the raw PDF bytes (Buffer).

import { jsPDF } from 'jspdf';

export function makePDF() {
  const doc = new jsPDF({ orientation: 'p', unit: 'mm', format: 'a4' });
  const M = 22;    // left margin (mm)
  const W = 166;   // content width (mm)
  let y = 22;

  const newPage = () => { doc.addPage(); y = 22; };
  const check   = () => { if (y > 268) newPage(); };

  // Centered text
  const center = (text, size = 11, bold = true) => {
    doc.setFontSize(size);
    doc.setFont('helvetica', bold ? 'bold' : 'normal');
    doc.splitTextToSize(text, W).forEach(line => {
      doc.text(line, M + W / 2, y, { align: 'center' });
      y += size * 0.42 + 1;
    });
  };

  // Left-aligned text with optional indent
  const left = (text, size = 10, bold = false, indent = 0) => {
    doc.setFontSize(size);
    doc.setFont('helvetica', bold ? 'bold' : 'normal');
    const lines = doc.splitTextToSize(text, W - indent);
    doc.text(lines, M + indent, y);
    y += lines.length * (size * 0.42 + 1) + 1;
  };

  // Right-aligned text (same y — use before advancing y with left/center)
  const right = (text, size = 10) => {
    doc.setFontSize(size);
    doc.setFont('helvetica', 'normal');
    doc.text(text, M + W, y, { align: 'right' });
  };

  // Horizontal rule
  const hr = (gap = 4) => {
    doc.setDrawColor(90);
    doc.line(M, y, M + W, y);
    y += gap;
  };

  // Vertical spacer
  const sp = (mm = 5) => { y += mm; };

  // Standard BailBridge draft footer
  const footer = () => {
    doc.setFontSize(7);
    doc.setTextColor(130);
    doc.text(
      'DRAFT — GENERATED BY BAILBRIDGE AI / NAMMA NYAYA AGENT — NOT FOR SUBMISSION WITHOUT ADVOCATE REVIEW',
      M + W / 2, 286, { align: 'center' }
    );
    doc.setTextColor(0);
  };

  // Return raw PDF bytes as a Node.js Buffer
  const build = () => {
    const ab = doc.output('arraybuffer');
    return Buffer.from(ab);
  };

  return {
    doc, center, left, right, hr, sp, check, newPage, footer, build,
    M, W,
    get y()  { return y; },
    set y(v) { y = v; },
  };
}
